# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eac0d0751ab03dcd292ce145736b6223b343e724a666233b16227449f7c6c6ce4680de7860677df11b16b18225fd2caccb8057a74998bc807d3b96461111827

test:
  secret_key_base: 5c61c30c8ffdb8b5ccfd9e0895410e7ad6d573460431ac1284e96ebc636a08666539b3e6847b0f31d68534ac2df383dc9e50489ecc2bccbe9df409fa9e853926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
